In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Engineering\ALL IT\SEM 6\DSBDA\student-dataset.csv")
print(df)

      id               name               nationality                 city  \
0      0          Kiana Lor                     China               Suzhou   
1      1     Joshua Lonaker  United States of America        Santa Clarita   
2      2      Dakota Blanco  United States of America              Oakland   
3      3    Natasha Yarusso  United States of America        Castro Valley   
4      4     Brooke Cazares                    Brazil  São José dos Campos   
..   ...                ...                       ...                  ...   
302  302        Austin Haas  United States of America             Columbus   
303  303    Madison Fithian  United States of America          Los Angeles   
304  304  Zachary Mulvahill  United States of America          Los Angeles   
305  305   Eliana Michelsen  United States of America              Oakland   
306  306    Dane Whittemore                    Canada              Toronto   

     latitude  longitude gender  ethnic.group  age  english.gra

In [54]:
import pandas as pd
data={"Roll-num":[10,20,30,40,50],"Age":[17,178,196,20,39],"Name":['sai','kiran','rohit','tusher','dipak']}
block=pd.DataFrame(data)
print("original data Frame:\n",)
print(block)

original data Frame:

   Roll-num  Age    Name
0        10   17     sai
1        20  178   kiran
2        30  196   rohit
3        40   20  tusher
4        50   39   dipak


In [18]:
print(" Extract data of specific rows of a dataframe")
block.loc[[0,1,3]]

 Extract data of specific rows of a dataframe


Roll-num  Age    Name
0        10   17     sai
1        20   18   kiran
3        40   20  tusher

In [17]:
print("rows using slicing")
block.loc[0:3]

rows using slicing


Roll-num  Age    Name
0        10   17     sai
1        20   18   kiran
2        30   19   rohit
3        40   20  tusher

In [16]:
print("particular columns using labels")
block.loc[0:2,['Age','Name']]

particular columns using labels


Age   Name
0   17    sai
1   18  kiran
2   19  rohit

In [15]:
print("iloc() function")
block.iloc[[0,1,3],[0,2]]


iloc() function


Roll-num    Name
0        10     sai
1        20   kiran
3        40  tusher

In [23]:
print("Shape")
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,10,13,23,24])
newarr=arr.reshape(4,3)
print(newarr)

Shape
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]
 [13 23 24]]


In [24]:
x=np.arange(12)
y=np.reshape(x,(4,3))

In [25]:
df=pd.read_csv(r"C:\Engineering\ALL IT\SEM 6\DSBDA\student-dataset.csv")
print(df)

      id               name               nationality                 city  \
0      0          Kiana Lor                     China               Suzhou   
1      1     Joshua Lonaker  United States of America        Santa Clarita   
2      2      Dakota Blanco  United States of America              Oakland   
3      3    Natasha Yarusso  United States of America        Castro Valley   
4      4     Brooke Cazares                    Brazil  São José dos Campos   
..   ...                ...                       ...                  ...   
302  302        Austin Haas  United States of America             Columbus   
303  303    Madison Fithian  United States of America          Los Angeles   
304  304  Zachary Mulvahill  United States of America          Los Angeles   
305  305   Eliana Michelsen  United States of America              Oakland   
306  306    Dane Whittemore                    Canada              Toronto   

     latitude  longitude gender  ethnic.group  age  english.gra

In [33]:
#concat
df2=block[:2]
df3=block[3:]
print(df2)
print(df3)


   Roll-num  Age   Name
0        10   17    sai
1        20   18  kiran
   Roll-num  Age    Name
3        40   20  tusher
4        50   39   dipak


In [40]:
df6=pd.concat([df2,df3],axis=0)
df4=block.iloc[:,:2]
df5=block.iloc[:,2:]
print(df4)
print(df5)

   Roll-num  Age
0        10   17
1        20   18
2        30   19
3        40   20
4        50   39
     Name
0     sai
1   kiran
2   rohit
3  tusher
4   dipak


In [44]:
df6=pd.concat([df2,df3],axis=1)
df2=block.iloc[:,:3]
df3=block.iloc[:,2:]
print(df2)
print(df3)

   Roll-num  Age    Name
0        10   17     sai
1        20   18   kiran
2        30   19   rohit
3        40   20  tusher
4        50   39   dipak
     Name
0     sai
1   kiran
2   rohit
3  tusher
4   dipak


In [52]:
data1={"Roll-num":[10,20,30],"Name":['sai','kiran','tusher']}
block1=pd.DataFrame(data1)

In [53]:
#merge 
marged=block.merge(block1,on='Name',how='inner')
print(marged)

   Roll-num_x  Age    Name  Roll-num_y
0          10   17     sai          10
1          20   18   kiran          20
2          40   20  tusher          30


In [55]:
#sort
sort=block.sort_values(by='Age',ascending=True)
print(sort)

   Roll-num  Age    Name
0        10   17     sai
3        40   20  tusher
4        50   39   dipak
1        20  178   kiran
2        30  196   rohit


In [57]:
#transpose 
tran=block.T
print(tran)

            0      1      2       3      4
Roll-num   10     20     30      40     50
Age        17    178    196      20     39
Name      sai  kiran  rohit  tusher  dipak


In [2]:
#casting data to wide format
import pandas as pd
block=pd.read_csv(r"C:\Engineering\ALL IT\SEM 6\DSBDA\abc.txt",sep=" ",names=['id','date','name','money'])
cast=block.pivot(index='date',columns='name',values='money').reset_index()
print(cast)


name      date     aa     bb     cc
0     1/2/2023  200.0  300.0    NaN
1     2/2/2023    NaN    NaN  900.0
2     3/2/2023    NaN    NaN  566.0
name      date     aa     bb     cc
0     1/2/2023  200.0  300.0    NaN
1     2/2/2023    NaN    NaN  900.0
2     3/2/2023    NaN    NaN  566.0


In [4]:
df.describe()

id    latitude   longitude  ethnic.group         age  \
count  307.000000  307.000000  307.000000           0.0  307.000000   
mean   153.000000   32.863388  -64.539121           NaN   21.964169   
std     88.767487   13.498582   81.249146           NaN    1.248013   
min      0.000000  -33.450000 -123.130000           NaN   19.000000   
25%     76.500000   32.720000 -118.240000           NaN   21.000000   
50%    153.000000   34.390000  -99.140000           NaN   22.000000   
75%    229.500000   38.960000  -73.855000           NaN   23.000000   
max    306.000000   59.890000  139.750000           NaN   26.000000   

       english.grade  math.grade  sciences.grade  language.grade  \
count     307.000000  307.000000      307.000000      307.000000   
mean        3.369707    3.414332        3.446580        4.396417   
std         0.538724    0.476839        0.509081        0.996474   
min         1.500000    2.100000        1.400000        1.000000   
25%         3.100000    3.100000        3.200000        4.000000   
50%         3.500000    3.500000        3.600000        5.000000   
75%         3.800000    3.800000        3.800000        5.000000   
max         4.000000    4.000000        4.000000        5.000000   

       portfolio.rating  coverletter.rating  refletter.rating  
count        307.000000          307.000000        307.000000  
mean           3.986971            4.110749          4.188925  
std            0.928749            0.823936          0.842193  
min            1.000000            1.000000          1.000000  
25%            3.500000            4.000000          4.000000  
50%            4.000000            4.000000          4.000000  
75%            5.000000            5.000000          5.000000  
max            5.000000            5.000000          5.000000

In [6]:
df.shape

(307, 16)