In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Engineering\ALL IT\SEM 6\DSBDA\student-dataset.csv")
print(df)

In [ ]:
import pandas as pd
data={"Roll-num":[10,20,30,40,50],"Age":[17,178,196,20,39],"Name":['sai','kiran','rohit','tusher','dipak']}
block=pd.DataFrame(data)
print("original data Frame:\n",)
print(block)

In [18]:
print(" Extract data of specific rows of a dataframe")
block.loc[[0,1,3]]

 Extract data of specific rows of a dataframe


Roll-num  Age    Name
0        10   17     sai
1        20   18   kiran
3        40   20  tusher

In [17]:
print("rows using slicing")
block.loc[0:3]

rows using slicing


Roll-num  Age    Name
0        10   17     sai
1        20   18   kiran
2        30   19   rohit
3        40   20  tusher

In [16]:
print("particular columns using labels")
block.loc[0:2,['Age','Name']]

particular columns using labels


Age   Name
0   17    sai
1   18  kiran
2   19  rohit

In [15]:
print("iloc() function")
block.iloc[[0,1,3],[0,2]]


iloc() function


Roll-num    Name
0        10     sai
1        20   kiran
3        40  tusher

In [23]:
print("Shape")
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,10,13,23,24])
newarr=arr.reshape(4,3)
print(newarr)

Shape
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]
 [13 23 24]]


In [24]:
x=np.arange(12)
y=np.reshape(x,(4,3))

In [ ]:
df=pd.read_csv(r"C:\Engineering\ALL IT\SEM 6\DSBDA\student-dataset.csv")
print(df)

In [33]:
#concat
df2=block[:2]
df3=block[3:]
print(df2)
print(df3)


   Roll-num  Age   Name
0        10   17    sai
1        20   18  kiran
   Roll-num  Age    Name
3        40   20  tusher
4        50   39   dipak


In [40]:
df6=pd.concat([df2,df3],axis=0)
df4=block.iloc[:,:2]
df5=block.iloc[:,2:]
print(df4)
print(df5)

   Roll-num  Age
0        10   17
1        20   18
2        30   19
3        40   20
4        50   39
     Name
0     sai
1   kiran
2   rohit
3  tusher
4   dipak


In [44]:
df6=pd.concat([df2,df3],axis=1)
df2=block.iloc[:,:3]
df3=block.iloc[:,2:]
print(df2)
print(df3)

   Roll-num  Age    Name
0        10   17     sai
1        20   18   kiran
2        30   19   rohit
3        40   20  tusher
4        50   39   dipak
     Name
0     sai
1   kiran
2   rohit
3  tusher
4   dipak


In [52]:
data1={"Roll-num":[10,20,30],"Name":['sai','kiran','tusher']}
block1=pd.DataFrame(data1)

In [53]:
#merge 
marged=block.merge(block1,on='Name',how='inner')
print(marged)

   Roll-num_x  Age    Name  Roll-num_y
0          10   17     sai          10
1          20   18   kiran          20
2          40   20  tusher          30


In [55]:
#sort
sort=block.sort_values(by='Age',ascending=True)
print(sort)

   Roll-num  Age    Name
0        10   17     sai
3        40   20  tusher
4        50   39   dipak
1        20  178   kiran
2        30  196   rohit


In [57]:
#transpose 
tran=block.T
print(tran)

            0      1      2       3      4
Roll-num   10     20     30      40     50
Age        17    178    196      20     39
Name      sai  kiran  rohit  tusher  dipak


In [2]:
#casting data to wide format
import pandas as pd
block=pd.read_csv(r"C:\Engineering\ALL IT\SEM 6\DSBDA\abc.txt",sep=" ",names=['id','date','name','money'])
cast=block.pivot(index='date',columns='name',values='money').reset_index()
print(cast)


name      date     aa     bb     cc
0     1/2/2023  200.0  300.0    NaN
1     2/2/2023    NaN    NaN  900.0
2     3/2/2023    NaN    NaN  566.0
name      date     aa     bb     cc
0     1/2/2023  200.0  300.0    NaN
1     2/2/2023    NaN    NaN  900.0
2     3/2/2023    NaN    NaN  566.0


In [ ]:
df.describe()

In [6]:
df.shape

(307, 16)